version: "3"
services:
  mysqlbackup:
    build:
      context: ./bin
    container_name: container_backup
    volumes:
      - ./data/backup:/backup
    environment:
      - DB_SERVER=mysql
      - DB_USER=root
      - DB_PASS=root
      - DB_DUMP_BY_SCHEMA=true
    external_links:
      - mysql

